#!/usr/bin/env python3
"""
Smoke test Ask AI with strategic executive questions.
"""

import requests
import json
import time

def test_ask_ai(question):
    """Test Ask AI functionality via API simulation."""
    
    # Simulate the Ask AI request (this would normally go through Streamlit)
    # For testing, we'll call the underlying logic directly
    
    print(f"\n🔍 QUESTION: {question}")
    print("=" * 80)
    
    # Import and test the AI logic
    import sys
    sys.path.append('.')
    
    try:
        from components.cluster_synthesizer import semantic_search
        import numpy as np
        
        # Load embeddings and insights
        embeddings = np.load('precomputed_embeddings.npy')
        with open('precomputed_insights.json', 'r', encoding='utf-8') as f:
            insights = json.load(f)
        
        # Simulate semantic search
        def simple_search(query, top_k=10):
            # Simple keyword-based search for testing
            query_lower = query.lower()
            scores = []
            for insight in insights:
                score = 0
                text = (insight.get('text', '') + ' ' + insight.get('title', '')).lower()
                if word in text:
                    score += text.count(word) * 0.1
                scores.append(score)
            
            top_indices = np.argsort(scores)[-top_k:][::-1]
            return [(insights[i], scores[i]) for i in top_indices if scores[i] > 0]
        
        # Search for relevant signals
        relevant_signals = simple_search(question, top_k=15)
        
        if relevant_signals:
            print(f"Found {len(relevant_signals)} relevant signals")
            print("\n📊 TOP SIGNALS:")
            for i, (signal, score) in enumerate(relevant_signals[:5], 1):
                title = signal.get('title', '')[:80]
                source = signal.get('source', '')
                sentiment = signal.get('sentiment', '')
                print(f"{i}. [{source}] {sentiment} - {title}")
        else:
            print("No direct signals found - would use broader semantic search")
        
        # Simulate AI response generation
        print(f"\n🤖 SIMULATED AI RESPONSE:")
        print("(This would be generated by GPT-4 using the found signals)")
        
    except Exception as e:
        print(f"❌ Error testing: {e}")

# Executive-level questions for eBay Collectibles
questions = [
    "What are the biggest pain points for high-volume sellers in our collectibles marketplace?",
    "How are buyers responding to our authentication guarantee program?",
    "What competitive threats should we prioritize from emerging platforms like Whatnot and Fanatics?",
    "What signals indicate we're losing market share in trading cards to specialized platforms?",
    "How is our vault storage product being perceived by power collectors?"
]

print("🚀 SMOKE TESTING ASK AI - EXECUTIVE STRATEGIC QUESTIONS")
print("=" * 80)

for question in questions:
    test_ask_ai(question)
    time.sleep(1)

print("\n✅ Smoke test complete!")
